### ISSUE TITLE
Tweak dev docs sidebar

### ISSUE THREAD

**Issue by juanmanso** [masa-finance/docs#201]
It should rather say `Masa AI` or nothing (awaiting grooming for stakeholders to asses)

| ![Image](https://github.com/masa-finance/docs/assets/21087992/6eba9067-fc1f-4f74-9430-5b2fde2e651c) |
| :--: |

**Comment by Luka-Loncar** [comment]
let's change this title to "Masa Network" please

**Comment by juanmanso** [comment]
> let's change this title to "Masa Network" please

I think it's safe to remove the triage label now. Holding on confirmation to do so
